config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :articles
  end

  scope module: 'admin' do
    resources :articles, only: [:show, :index] do
      resources :comments
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :articles, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    if user_type == 1
      return true
    end
    false
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  # documentation
  class ArticlesController < ApplicationController
    def index
      @articles = Article.all
      @user = current_user
    end

    def new
      auth_user
      @article = Article.new
    end

    def show
      @article = Article.find(params[:id])
      @user = User.find(@article.user_id)
    end

    def edit
      article = auth_article(params[:id])
      auth_user
      @article = article
    end

    def update
      @article = auth_article(params[:id])
      auth_user
      if @article.update(article_params)
        redirect_to admin_article_path(@article)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @article = auth_article(params[:id])
      auth_user
      @article&.destroy
      redirect_to articles_path, status: :see_other
    end

    def create
      @article = Article.new(article_params)
      auth_user
      if @article.save
        redirect_to articles_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    private

    def article_params
      params.require(:article).permit(:title, :body).merge(user_id: current_user.id)
    end

    def auth_user
      raise Pundit::NotAuthorizedError, 'not allowed' unless UserPolicy.new(current_user).allowed?
    end

    def auth_article(id)
      article = Article.find(id)
      return article if article.user_id == current_user.id

      false
    end
  end
end

app/controllers/admin/comments_controller.rb
module Admin
  class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(valid_params)
      redirect_to articles_path(@article)
    end

    def destroy
      @article = Article.find(params[:article_id])
      @comment = auth_comment(params[:id])
      if @comment
        @comment.destroy
        redirect_to articles_path(@article)
      else
        redirect_to articles_path, status: :see_other
      end
    end

    private

    def auth_comment(id)
      comment = @article.comments.find(id)
      return comment if comment.user_id == current_user.id
      false
    end

    def valid_params
      params.require(:comment).permit(:body).merge(:user_id => current_user.id).merge(:article_id => @article.id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  def index
    redirect_to articles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/articles/edit.html.erb
<h1>Edit article</h1>
<%= form_with url: admin_article_path, model: @article, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= @article.errors.full_messages_for(:title) do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <%= @article.errors.full_messages_for(:body) do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/index.html.erb
<h1> Hi and hello</h1>
<div>
  Oh you are signed in how cool
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <%= @user.email %>
</div>

<% if current_user.user_type == 1 %>

  <%= link_to "New article", new_admin_article_url %>
<% end %>

<% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article %> - <%= User.find(article.user_id).email %>
  </li>
<% end %>

app/views/admin/articles/new.html.erb
<h1>New article</h1>
<%= form_with url: admin_articles_path, model: @article, local: true do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= @article.errors.full_messages_for(:title) do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <%= @article.errors.full_messages_for(:body) do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/show.html.erb
<h2><%= @article.title %></h2>
<h6><%= @user.email %></h6>
<% if current_user.id == @user.id %>
  <%= link_to "Edit", edit_admin_article_path(@article) %>
  <%= link_to "Delete", admin_article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure"
  } %>
<% end %>
<div>
  <%= @article.body %>
</div>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    - <i><%= User.find(comment.user_id).email %></i>
    <% if current_user.id == comment.user_id %>
      <%= link_to "Delete", [comment.article, comment], data: {
        turbo_method: :delete,
        turbo_confirms: "Are you sure?"
      } %>
    <% end %>
  </p>
<% end %>



<h2>Add a comment:</h2>
<%= form_with model: [@article, @article.comments.build] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/admin/index.html.erb
<div>
  index
</div>

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= @article.errors.full_messages_for(:title) do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <%= @article.errors.full_messages_for(:body) do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>


<% end %>

app/views/articles/index.html.erb
<h1> Hi and hello</h1>
<div>
  Oh you are signed in how cool
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <%= @user.email %>
</div>

<%= link_to "New article", new_article_path %>

<% @articles.each do |article| %>
  <li>
    <%= link_to article.title, article %> - <%= User.find(article.user_id).email %>
  </li>
<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<h6><%= @user.email %></h6>
<% if current_user.id == @user.id %>
  <%= link_to "Edit", edit_article_path(@article) %>
  <%= link_to "Delete", article_path(@article), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure"
  } %>
<% end %>
<div>
  <%= @article.body %>
</div>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
    - <i><%= User.find(comment.user_id).email %></i>
    <% if current_user.id == comment.user_id %>
      <%= link_to "Delete", [comment.article, comment], data: {
        turbo_method: :delete,
        turbo_confirms: "Are you sure?"
      } %>
    <% end %>
  </p>
<% end %>



<h2>Add a comment:</h2>
<%= form_with model: [@article, @article.comments.build] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comment/article_id:references.html.erb
<h1>Comment#article_id:references</h1>
<p>Find me in app/views/comment/article_id:references.html.erb</p>

app/views/comment/body:text.html.erb
<h1>Comment#body:text</h1>
<p>Find me in app/views/comment/body:text.html.erb</p>

app/views/comment/user_id:references.html.erb
<h1>Comment#user_id:references</h1>
<p>Find me in app/views/comment/user_id:references.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogDocker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>